name = "SymbolicUtils"
uuid = "d1185830-fcd6-423d-90d6-eec64667417b"
authors = ["Shashi Gowda"]
version = "4.18.3"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ReadOnlyArrays = "988b38a3-91fc-5605-94a2-ee2116b3bd83"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
TaskLocalValues = "ed4db957-447d-4319-bfb6-7fa9ae7ecf34"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
WeakCacheSets = "d30d5f5c-d141-4870-aa07-aabb0f5fe7d5"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[extensions]
SymbolicUtilsChainRulesCoreExt = "ChainRulesCore"
SymbolicUtilsDistributionsExt = "Distributions"
SymbolicUtilsLabelledArraysExt = "LabelledArrays"
SymbolicUtilsReverseDiffExt = "ReverseDiff"

[compat]
AbstractTrees = "0.4"
ArrayInterface = "7.8"
ChainRulesCore = "1"
Combinatorics = "1 - 1.0.2"
ConstructionBase = "1.5.7"
DataStructures = "0.18, 0.19"
DocStringExtensions = "0.8, 0.9"
DynamicPolynomials = "0.6.4"
EnumX = "1.0.5"
ExproniconLite = "0.10.14"
LabelledArrays = "1.5"
LinearAlgebra = "1"
MacroTools = "0.5.16"
Moshi = "0.3.6"
MultivariatePolynomials = "0.5.12"
MutableArithmetics = "1.6.5"
NaNMath = "0.3, 1.1.2"
OhMyThreads = "0.7"
PrecompileTools = "1.2.1"
ReadOnlyArrays = "0.2.0"
ReverseDiff = "1"
RuntimeGeneratedFunctions = "0.5.13"
Setfield = "0.7, 0.8, 1"
SnoopCompileCore = "3.0.0"
SparseArrays = "1"
SpecialFunctions = "0.10, 1.0, 2"
StaticArrays = "1.0"
StaticArraysCore = "1.4.3"
SymbolicIndexingInterface = "0.3"
TaskLocalValues = "0.1.2"
TermInterface = "2.0"
WeakCacheSets = "0.1.0"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
SnoopCompileCore = "e2b509da-e806-4183-be48-004708413034"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["BenchmarkTools", "Documenter", "LabelledArrays", "Pkg", "PkgBenchmark", "Random", "ReferenceTests", "ReverseDiff", "SafeTestsets", "Test", "Zygote", "OhMyThreads", "RuntimeGeneratedFunctions", "StaticArrays", "SnoopCompile", "SnoopCompileCore"]
